# Generated by Django 5.1.3 on 2024-12-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elemento',
            old_name='user',
            new_name='empleado',
        ),
    ]
