# Generated by Django 5.1.3 on 2024-12-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_asignacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elemento',
            old_name='empleado',
            new_name='user',
        ),
    ]
