# Generated by Django 5.1.3 on 2024-12-13 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_empleado_elemento_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('serial', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('tipo', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
