# Generated by Django 5.1.3 on 2024-12-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_equipo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='user',
        ),
    ]
