# Generated by Django 5.1.3 on 2024-12-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='computador',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
