# Generated by Django 5.1.4 on 2024-12-18 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_asignacion_computador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.empleado'),
        ),
    ]
